### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by gudbrandtandberg** [gudbrandtandberg/Asperoy#1]
Syns det er et ganske stygt navn. Er det noen god grunn til at xmlCrud heter det? Hvis ikke syns jeg vi skal bruke et bedre navn.

**Comment by eibakke** [comment]
CRUD - Create Read Update Delete

http://en.wikipedia.org/wiki/Create,_read,_update_and_delete

Et alternativ kan kanskje være XML_Manager elns? Men det er vel et heller trivielt problem, dessuten synes jeg CRUD beskriver godt hva som er formålet med klassen.

**Comment by gudbrandtandberg** [comment]
Åja, hehe.. Jeg fikk assosiasjoner til 

crud [noun]
1. a substance which is considered unpleasant or disgusting, typically because of its dirtiness..

Men la det gå for nå da :) Vill bare raise et issue.
