### ISSUE TITLE
Bilder not found

### ISSUE THREAD

**Issue by gudbrandtandberg** [gudbrandtandberg/Asperoy#2]
Jeg se albumoversikt, men ikke inni noen av albumene. Har sannsynligvis ingenting med permissions å gjøre lenger, jeg får 

Not Found
The requested URL /bilder/Sommer2012 was not found on this server.

-error. Hva kan det være?

**Comment by eibakke** [comment]
Det er nok et problem med .htaccess filen i public directoriet. Virker som om den aldri kommer til rewriterulen som gjør at bilder/index.php filen får tilgang til variablene albumnavn og bildenavn. Kan tenkes at det har noe med Apache 2.2 vs Apache 2.4 igjen? Du har ikke tenkt på å oppdatere til seneste stabile versjon? Ellers er det en guide for mod_rewrite i 2.2 her : http://httpd.apache.org/docs/2.2/rewrite/intro.html

**Comment by gudbrandtandberg** [comment]
Ahh! Deilig, nå klarte jeg det. Masse notices, men det funker væffal. Rewriten trengte å få en liten AllowOverride all for å lese htaccess. Og det virker på asperøy.no nå. Du kommer hjem torsdag? Så snakkes vi etter det en gang. Har en forespørsel: gidder du å gå igjennom og småkommentere underveis, spesielt når det gjelder styring/kontroll/logikk osv. Takktakk.

**Comment by eibakke** [comment]
Herlig! Takk for at du er tålmodig med dette.

Jeg skal se til å kommentere mer hvor det ikke er synlig hva som skjer. Vet jeg er litt dårlig til det.

Neste steg i oppfiksing (vs. utvikling) er kanskje å fikse opplastningstiden? Lager en ny issue
